spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 131400
#    131400
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.qq.com
    port: 587
    username: 1452588824@qq.com
    password: xlmhzkilpwvlbaff
    default-encoding: UTF-8
    properties.mail.stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.debug: true
server:
  port: 8081
mybatis:
  # 存放实体的位置
  type-aliases-package: com.crm_system.springbootback.entity
  # 存放 mapper 映射文件的位置
  mapper-locations: classpath:mapper/*.xml