spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081